; PlatformIO Project Configuration File
; Coffee Grinder Timer - ESP32-C3

[env:grinder]
platform = espressif32
board = adafruit_qtpy_esp32c3
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_unflags =
  -std=gnu++11
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -std=gnu++17
  -Wall
  -Wextra
  -I${sysenv.CREDENTIALS_INCLUDE}
lib_deps =
  me-no-dev/ESPAsyncWebServer
  ayushsharma82/WebSerial
